language: julia

os:
  - linux
  - osx
  - windows
  - freebsd

julia:
  - 1.0
  - 1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

branches:
  only:
    - master

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("AMD")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
